export default [
  { name: "", code: "PREFIXmatrix.pngSUFIX", icon: "matrix.png" },
  { name: "", code: "PREFIXmatrix_1_matrix.svgSUFIX", icon: "matrix_1_matrix.svg" },
  { name: "", code: "PREFIXmatrix_2_bmatrix.svgSUFIX", icon: "matrix_2_bmatrix.svg" },
  { name: "", code: "PREFIXmatrix_3_pmatrix.svgSUFIX", icon: "matrix_3_pmatrix.svg" },
  { name: "", code: "PREFIXmatrix_4_vmatrix.svgSUFIX", icon: "matrix_4_vmatrix.svg" },
  { name: "", code: "PREFIXmatrix_5_bigVmatrix.svgSUFIX", icon: "matrix_5_bigVmatrix.svg" },
  { name: "", code: "PREFIXmatrix_6_bigBmatrix.svgSUFIX", icon: "matrix_6_bigBmatrix.svg" },
  { name: "", code: "PREFIXmatrix_7_leftmatrix.svgSUFIX", icon: "matrix_7_leftmatrix.svg" },
  { name: "", code: "PREFIXmatrix_8_rightmatrix.svgSUFIX", icon: "matrix_8_rightmatrix.svg" },
  { name: "", code: "PREFIXmatrix_9_case.svgSUFIX", icon: "matrix_9_case.svg" },
  { name: "", code: "PREFIXmatrix_10_align.svgSUFIX", icon: "matrix_10_align.svg" },

  { name: "", code: "PREFIXalgebra.pngSUFIX", icon: "algebra.png" },
  { name: "", code: "PREFIXgeometry.pngSUFIX", icon: "geometry.png" },
  { name: "", code: "PREFIXinequality.pngSUFIX", icon: "inequality.png" },
  { name: "", code: "PREFIXcalculous.pngSUFIX", icon: "calculous.png" },
  { name: "", code: "PREFIXarray.pngSUFIX", icon: "array.png" },
  { name: "", code: "PREFIXtrigonometry.pngSUFIX", icon: "trigonometry.png" },
  { name: "", code: "PREFIXstatistics.pngSUFIX", icon: "statistics.png" },
  { name: "", code: "PREFIXsequence.pngSUFIX", icon: "sequence.png" },
  { name: "", code: "PREFIXphysics.pngSUFIX", icon: "physics.png" },
  { name: "", code: "PREFIXchemistry.pngSUFIX", icon: "chemistry.png" },
  { name: "", code: "PREFIXwechat.pngSUFIX", icon: "wechat.png" },
  { name: "", code: "PREFIXtoutiao.pngSUFIX", icon: "toutiao.png" },
  { name: "", code: "PREFIXpolice.pngSUFIX", icon: "police.png" },
  { name: "", code: "PREFIXbrowsers.pngSUFIX", icon: "browsers.png" },
  { name: "", code: "PREFIXempty1.pngSUFIX", icon: "empty1.png" },
];
